Vagrant.configure('2') do |config|

  # configure box to use host http_proxy if
  # vagrant-proxyconf is enabled
  def configure_proxy(vm_def)
    if Vagrant.has_plugin?("vagrant-proxyconf") && ENV['http_proxy']
      vm_def.proxy.http = ENV['http_proxy']
      vm_def.proxy.https = ENV['https_proxy']
      vm_def.apt_proxy.http = ENV['http_proxy']
      vm_def.apt_proxy.https = ENV['https_proxy']
      vm_def.proxy.no_proxy = ENV['no_proxy']
    end
  end

  DEFAULT_VAGRANT_BOX = "rackhd/rackhd"

  def set_box(vm_def)
    vm_def.vm.box = ENV['VAGRANT_BOX'] || DEFAULT_VAGRANT_BOX
    if ENV['VAGRANT_BOX_VERSION']
      vm_def.vm.box_version = ENV['VAGRANT_BOX_VERSION']
      vm_def.vm.box_check_update = false
    end
  end

  def configure_vm_size(vm_def)
    if ENV['VAGRANT_VM_MEM']
      vm_def.vm.provider 'virtualbox' do |vb|
        vb.memory = ENV['VAGRANT_VM_MEM']
      end
    end
  end

  if ENV['VAGRANT_VM_CPU']
    vm_def.vm.provider 'virtualbox' do |vb|
      vb.cpus = ENV['VAGRANT_VM_CPU']
    end
  end

  config.vm.box = "rackhd/rackhd"
  
  config.vm.define :rackhd01 do |rackhd01|
    config.vm.box_check_update = true
    rackhd01.vm.synced_folder "builds", "/builds"
    rackhd01.vm.synced_folder "../../on-imagebuilder", "/repo"
    rackhd01.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y install python-pip
    sudo pip install ansible==1.9.4
    cd /repo
    sudo ansible-playbook -i hosts all.yml
    mv /tmp/on-imagebuilder/builds/* /builds/
  SHELL
end
