Vagrant.configure('2') do |config|

  # configure box to use host http_proxy if
  # vagrant-proxyconf is enabled
  def configure_proxy(vm_def)
    if Vagrant.has_plugin?("vagrant-proxyconf") && ENV['http_proxy']
      vm_def.proxy.http = ENV['http_proxy']
      vm_def.proxy.https = ENV['https_proxy']
      vm_def.apt_proxy.http = ENV['http_proxy']
      vm_def.apt_proxy.https = ENV['https_proxy']
      vm_def.proxy.no_proxy = ENV['no_proxy']
    end
  end

  DEFAULT_VAGRANT_BOX = 'ubuntu/trusty64'

  def set_box(vm_def)
    vm_def.vm.box = ENV['VAGRANT_BOX'] || DEFAULT_VAGRANT_BOX
    if ENV['VAGRANT_BOX_VERSION']
      vm_def.vm.box_version = ENV['VAGRANT_BOX_VERSION']
      vm_def.vm.box_check_update = false
    end
  end

  def configure_vm_size(vm_def)
    if ENV['VAGRANT_VM_MEM']
      vm_def.vm.provider 'virtualbox' do |vb|
        vb.memory = ENV['VAGRANT_VM_MEM']
      end
    end
    if ENV['VAGRANT_VM_CPU']
      vm_def.vm.provider 'virtualbox' do |vb|
        vb.cpus = ENV['VAGRANT_VM_CPU']
      end
    end
  end

  config.vm.define :imagebuilder01 do |imagebuilder01|

    configure_proxy(imagebuilder01)
    set_box(imagebuilder01)
    configure_vm_size(imagebuilder01)
    imagebuilder01.vm.network :private_network, ip: '192.168.37.2'
    imagebuilder01.vm.hostname = 'imagebuilder01'
    end
    rackhd01.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end
      config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    sudo ansible-playbook -i hosts all.yml
  SHELL
  end
end
